[10.Kubernetes.ws] add check_pods logic

diff --git a/.github/workflows/check_pods_status.yml b/.github/workflows/check_pods_status.yml
--- a/.github/workflows/check_pods_status.yml
+++ b/.github/workflows/check_pods_status.yml
@@ -8,3 +8,20 @@ jobs:
     steps:
       - name: Print info
         run: echo "Run _10-kubernetes-ws-homework-1-check-pods-status"
+
+      -name: Get pods info
+       id: pods_info_step
+       run: |
+         has_failed=$(kubectl get pods -A -o custom-columns='STATUS:.status.phase' | grep -Eq "Failed|CrashLoopBackOff|Unknown" && echo 1 || echo 0)
+         echo "has_failed=$has_failed" >> "$GITHUB_OUTPUT"
+         echo "pods_info=$(kubectl get pods -A)" >> "$GITHUB_OUTPUT"
+
+      -name: Send slack notification
+       run: |
+         has_failed=${{steps.pods_info_step.outputs.has_failed}}
+         pods_info=${{steps.pods_info_step.outputs.pods_info}}
+
+         message_body_pattern="{\"text\":\"%s\nCurrent pods info: ```%s```"}"
+         pods_status="$( [[ ${has_failed} = 1 ]] && echo ":red_circle: ATTENTION! Crushed pods were detected" || echo ":green_circle: No crushed pods were detected")"
+         message_body=$(printf "${message_body_pattern}" "${pods_status}" "${pods_info}")
+         curl -X POST -H 'Content-type: application/json' --data '${message_body}' ${SECRET_SLACK_WEBHOOK_URL}
